'use client'

import { useMemo, useState } from 'react'
import { GoalProgress } from '@/components/goal-progress'
import { useLocalData } from '@/components/local-data'
import { allocatedTotal, type Goal } from '@/lib/goals'
import { centsToInput, fmt, parseAmount } from '@/lib/money'
import { totalsFrom } from '@/lib/types'

export function LocalGoalView() {
  const { goals, items, saveGoals } = useLocalData()
  const [editing, setEditing] = useState<Goal | null>(null); const [error, setError] = useState<string | null>(null); const [pending, setPending] = useState(false)
  const totals = useMemo(() => totalsFrom(items), [items]); const available = Math.max(0, totals.liquid - allocatedTotal(goals))
  async function submit(form: HTMLFormElement) { const data = new FormData(form); const target = parseAmount(String(data.get('target') ?? '')); const allocation = parseAmount(String(data.get('allocated') ?? '')); const name = String(data.get('name') ?? '').trim(); if (!name || name.length > 80) return setError('Give this goal a name of up to 80 characters.'); if (!target.ok || target.cents <= 0) return setError(target.ok ? 'Your target must be greater than zero.' : target.error); if (!allocation.ok) return setError(allocation.error); if (allocation.cents > target.cents) return setError('You cannot allocate more than this goal’s target.'); const other = allocatedTotal(goals.filter((goal) => goal.id !== editing?.id)); if (other + allocation.cents > totals.liquid) return setError(`Only ${fmt(Math.max(0, totals.liquid - other))} is available to allocate.`); const goal: Goal = { id: editing?.id ?? crypto.randomUUID(), name, target_cents: target.cents, allocated_cents: allocation.cents, target_date: String(data.get('target_date') ?? '') || null, note: String(data.get('note') ?? '').trim() || null }; setPending(true); try { await saveGoals([...goals.filter((entry) => entry.id !== goal.id), goal]); setEditing(null); setError(null) } catch { setError('Could not save this goal locally.') } finally { setPending(false) } }
  return <div className="nw-screen nw-goal" style={{ maxWidth: 720 }}><div style={{ fontSize: 11, letterSpacing: '.16em', textTransform: 'uppercase', color: 'var(--nw-faint)' }}>Your allocations · local only</div><p style={{ color: 'var(--nw-muted)' }}>Progress is based on cash you assign here, not your net worth.</p><div style={{ marginTop: 18, padding: 18, border: '1px solid var(--nw-line)', borderRadius: 14 }}><div style={{ fontSize: 13, color: 'var(--nw-muted)' }}>Available to allocate</div><div style={{ fontSize: 28, fontWeight: 600 }}>{fmt(available)}</div></div>{goals.length > 0 && <div style={{ display: 'grid', gap: 12, marginTop: 20 }}>{goals.map((goal) => <div key={goal.id} style={{ padding: 18, border: '1px solid var(--nw-line)', borderRadius: 14 }}><GoalProgress goal={goal}/><div style={{ display: 'flex', gap: 12, marginTop: 12 }}><button onClick={() => setEditing(goal)}>Edit</button><button onClick={() => void saveGoals(goals.filter((entry) => entry.id !== goal.id))}>Remove</button></div></div>)}</div>}<div style={{ marginTop: 28, paddingTop: 24, borderTop: '1px solid var(--nw-line)' }}><div style={{ fontSize: 19 }}>{editing ? `Edit ${editing.name}` : 'Add a goal'}</div><form key={editing?.id ?? 'new'} onSubmit={(event) => { event.preventDefault(); void submit(event.currentTarget) }} style={{ marginTop: 16, display: 'grid', gap: 14 }}><label>Goal name<input className="nw-input" name="name" required defaultValue={editing?.name ?? ''}/></label><label>Target (PHP)<input className="nw-input" name="target" required inputMode="decimal" defaultValue={editing ? centsToInput(editing.target_cents) : ''}/></label><label>Allocated now (PHP)<input className="nw-input" name="allocated" required inputMode="decimal" defaultValue={editing ? centsToInput(editing.allocated_cents) : '0'}/></label><label>Target date (optional)<input className="nw-input" name="target_date" type="date" defaultValue={editing?.target_date ?? ''}/></label><label>Note (optional)<input className="nw-input" name="note" defaultValue={editing?.note ?? ''}/></label>{error && <p role="alert" style={{ color: 'var(--color-accent-2-600)' }}>{error}</p>}<div><button className="nw-btn-primary" disabled={pending}>{pending ? 'Saving…' : editing ? 'Save allocation' : 'Add goal'}</button>{editing && <button type="button" onClick={() => setEditing(null)} style={{ marginLeft: 10 }}>Cancel</button>}</div></form></div></div>
}
